---
# Install APT packages

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install base APT packages
  apt:
    name: "{{ base_apt_packages }}"
    state: present
  become: yes
  when: base_apt_packages | length > 0

